.PHONY: all
all:
	g++ -std=c++11 circuit_design_mod.cpp -o out

.PHONY: stress
stress:
	g++ -std=c++11 stress.cpp -o stress

.PHONY: ref
ref:
	g++ -std=c++11 reference.cpp -o ref

.PHONY: orig
orig:
	g++ -std=c++11 circuit_design.cpp -o orig
